"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function AdminOrderRefundForm({ orderId, remainingCents, currency = "EUR" }: { orderId: string; remainingCents: number; currency?: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!window.confirm("De terugbetaling wordt bij de betaalprovider uitgevoerd en maakt een creditnota. Doorgaan?")) return; const form = new FormData(event.currentTarget); const raw = String(form.get("amount") ?? "").trim().replace(",", "."); const parsedAmount = raw ? Math.round(Number(raw) * 100) : null; if (raw && (parsedAmount == null || !Number.isFinite(parsedAmount) || parsedAmount <= 0)) { setMessage("Vul een geldig bedrag in."); return; } const amountCents: number | null = parsedAmount; setBusy(true); setMessage(null); try { const response = await fetch(`/api/admin/orders/${orderId}/refund`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ amountCents, reason: form.get("reason"), bikeDestination: form.get("bikeDestination") }) }); const body = await response.json().catch(() => null) as { error?: string; result?: { status: string } } | null; if (!response.ok) { setMessage(body?.error ?? "Terugbetaling mislukt."); return; } setMessage(body?.result?.status === "REFUNDED" ? "Volledige terugbetaling en creditnota verwerkt." : "Deelterugbetaling en creditnota verwerkt."); router.refresh(); } catch { setMessage("De verbinding is mislukt."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="mt-5 rounded-xl border border-state-warning/40 bg-state-warning/10 p-5"><h3 className="font-semibold text-ink">Retour / terugbetaling</h3><p className="mt-1 text-sm text-ink-soft">Resterend terug te betalen: {(remainingCents / 100).toLocaleString("nl-NL", { style: "currency", currency })}. Laat bedrag leeg voor een volledige refund.</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-sm text-ink-soft">Bedrag (€)<input name="amount" inputMode="decimal" placeholder="Volledig bedrag" className="mt-1 block w-full rounded-lg border border-line bg-card px-3 py-2 text-ink" /></label><label className="text-sm text-ink-soft">Fiets na volledige retour<select name="bikeDestination" defaultValue="WORKSHOP" className="mt-1 block w-full rounded-lg border border-line bg-card px-3 py-2 text-ink"><option value="WORKSHOP">Werkplaats</option><option value="AVAILABLE">Beschikbaar</option><option value="ARCHIVED">Archiveren</option></select></label><label className="text-sm text-ink-soft sm:col-span-1">Reden<textarea name="reason" required maxLength={1000} rows={2} className="mt-1 block w-full rounded-lg border border-line bg-card px-3 py-2 text-ink" /></label></div><button disabled={busy} className="mt-3 rounded-lg bg-brand-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Verwerken…" : "Terugbetalen en creditnota maken"}</button>{message && <p className="mt-3 text-sm text-ink-soft">{message}</p>}</form>;
}
